import { Clinic, Doctor, Patient, PrescriptionTemplate, Visit } from '../types';

export const SEED_DOCTOR: Doctor = {
  id: 'doc-1',
  name: 'Dr. Sujit Joshi',
  qualifications: 'BHMS, MD (Hom.)',
  registrationNumber: 'MH/HOM/2012/8472',
  specialty: 'General Physician & Consultant',
  phone: '98765 43210',
  email: 'dr.sujit@opdlyclinic.in',
  signatureText: 'Dr. Sujit Joshi, MD',
};

export const SEED_CLINIC: Clinic = {
  id: 'clinic-1',
  name: 'OPDly Clinic',
  address: 'Shop 4, Galaxy Enclave, Paud Road, Kothrud, Pune, Maharashtra 411038',
  phone: '98765 43210',
  email: 'care@opdlyclinic.in',
  timings: 'Mon - Sat: 9:30 AM - 1:30 PM, 5:30 PM - 9:30 PM (Sun: 10 AM - 1 PM)',
  consultationFee: 500,
  followUpFee: 300,
};

export const SEED_PATIENTS: Patient[] = [
  {
    id: 'P-1001',
    name: 'Rahul Patil',
    mobile: '98765 43210',
    age: 42,
    gender: 'Male',
    dob: '1984-03-15',
    address: 'Kothrud, Pune, Maharashtra',
    emergencyContact: '98220 33445',
    emergencyRelation: 'Spouse',
    medicalProfile: {
      bloodGroup: 'O+',
      allergies: ['Penicillin'],
      chronicConditions: ['Hypertension'],
      currentMedications: ['Amlodipine 5mg once daily'],
    },
    isFavorite: true,
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-09-20T10:45:00.000Z',
    lastVisitDate: '2026-09-12',
    lastDiagnosis: 'Hypertension',
    totalVisitsCount: 3,
  },
  {
    id: 'P-1002',
    name: 'Sneha Joshi',
    mobile: '98765 76655',
    age: 28,
    gender: 'Female',
    dob: '1998-07-22',
    address: 'Bavdhan, Pune, Maharashtra',
    emergencyContact: '98901 22334',
    emergencyRelation: 'Father',
    medicalProfile: {
      bloodGroup: 'B+',
      allergies: [],
      chronicConditions: [],
    },
    isFavorite: false,
    createdAt: '2026-09-20T11:15:00.000Z',
    updatedAt: '2026-09-20T11:15:00.000Z',
    lastVisitDate: '2026-09-20',
    lastDiagnosis: 'Acute Pharyngitis',
    totalVisitsCount: 1,
  },
  {
    id: 'P-1003',
    name: 'Amit Shah',
    mobile: '97654 32109',
    age: 51,
    gender: 'Male',
    dob: '1975-11-04',
    address: 'Aundh, Pune, Maharashtra',
    medicalProfile: {
      bloodGroup: 'A+',
      allergies: ['Sulfa drugs'],
      chronicConditions: ['Type 2 Diabetes', 'Dyslipidemia'],
    },
    isFavorite: true,
    createdAt: '2026-07-05T09:30:00.000Z',
    updatedAt: '2026-09-10T12:20:00.000Z',
    lastVisitDate: '2026-09-10',
    lastDiagnosis: 'Type 2 Diabetes Review',
    totalVisitsCount: 4,
  },
  {
    id: 'P-1004',
    name: 'Pooja Mehta',
    mobile: '88721 65432',
    age: 34,
    gender: 'Female',
    dob: '1992-04-18',
    address: 'Baner, Pune, Maharashtra',
    medicalProfile: {
      bloodGroup: 'AB+',
      allergies: [],
      chronicConditions: ['Migraine'],
    },
    isFavorite: false,
    createdAt: '2026-08-20T14:15:00.000Z',
    updatedAt: '2026-09-05T16:00:00.000Z',
    lastVisitDate: '2026-09-05',
    lastDiagnosis: 'Migraine Attack',
    totalVisitsCount: 2,
  },
  {
    id: 'P-1005',
    name: 'Vikram Rao',
    mobile: '88990 11122',
    age: 46,
    gender: 'Male',
    dob: '1980-09-10',
    address: 'Shivajinagar, Pune, Maharashtra',
    medicalProfile: {
      bloodGroup: 'O-',
      allergies: ['Aspirin'],
      chronicConditions: ['Acidity / GERD'],
    },
    isFavorite: false,
    createdAt: '2026-08-01T11:00:00.000Z',
    updatedAt: '2026-09-01T10:30:00.000Z',
    lastVisitDate: '2026-09-01',
    lastDiagnosis: 'Acid Peptic Disorder',
    totalVisitsCount: 2,
  },
];

export const SEED_TEMPLATES: PrescriptionTemplate[] = [
  {
    id: 'tpl-1',
    name: 'Fever',
    description: 'Standard protocol for acute viral pyrexia',
    medicines: [
      {
        id: 'm-f1',
        medicineName: 'Paracetamol 500 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '1-0-1',
        timing: 'After food',
        duration: '5 days',
        instructions: 'Take with warm water if fever exceeds 100°F',
      },
      {
        id: 'm-f2',
        medicineName: 'Pantoprazole 40 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '1-0-0',
        timing: 'Empty stomach',
        duration: '5 days',
        instructions: 'Take 30 mins before breakfast',
      },
    ],
    advices: [
      'Drink plenty of water (8-10 glasses daily)',
      'Take adequate rest and avoid physical exertion',
      'Light digestible diet (khichdi, clear soups)',
    ],
    investigations: ['CBC'],
  },
  {
    id: 'tpl-2',
    name: 'Cold & Cough',
    description: 'Upper respiratory allergic & infectious cough',
    medicines: [
      {
        id: 'm-cc1',
        medicineName: 'Cetirizine 10 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '0-0-1',
        timing: 'At night',
        duration: '5 days',
        instructions: 'May cause mild drowsiness',
      },
      {
        id: 'm-cc2',
        medicineName: 'Paracetamol 500 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '1-0-1',
        timing: 'After food',
        duration: '3 days',
      },
      {
        id: 'm-cc3',
        medicineName: 'Dextromethorphan + Chlorpheniramine Syrup',
        form: 'Syrup',
        dosage: '10 ml',
        frequency: '1-0-1',
        timing: 'After food',
        duration: '5 days',
        instructions: 'Shake bottle well before use',
      },
    ],
    advices: [
      'Steam inhalation twice daily for 10 minutes',
      'Warm saline gargles 3 times a day',
      'Avoid cold beverages, ice creams, and exposed air conditioners',
    ],
  },
  {
    id: 'tpl-3',
    name: 'Acidity',
    description: 'GERD, dyspepsia & gastric irritation',
    medicines: [
      {
        id: 'm-ac1',
        medicineName: 'Pantoprazole + Domperidone (Pan-D)',
        form: 'Capsule',
        dosage: '1 capsule',
        frequency: '1-0-0',
        timing: 'Empty stomach',
        duration: '7 days',
        instructions: 'Take 30 minutes before morning breakfast',
      },
      {
        id: 'm-ac2',
        medicineName: 'Antacid Gel (Magaldrate + Simethicone)',
        form: 'Syrup',
        dosage: '15 ml',
        frequency: '0-1-1',
        timing: 'After food',
        duration: '7 days',
        instructions: 'Take after lunch and dinner as needed',
      },
    ],
    advices: [
      'Avoid spicy, fried, and oily food',
      'Do not lie down immediately after eating (wait 2 hours)',
      'Eat small frequent meals instead of heavy dinners',
    ],
  },
  {
    id: 'tpl-4',
    name: 'Hypertension',
    description: 'Maintenance regimen for essential hypertension',
    medicines: [
      {
        id: 'm-ht1',
        medicineName: 'Telmisartan 40 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '1-0-0',
        timing: 'After food',
        duration: '30 days',
        instructions: 'Take consistently at the same morning hour',
      },
      {
        id: 'm-ht2',
        medicineName: 'Amlodipine 5 mg',
        form: 'Tablet',
        dosage: '1 tablet',
        frequency: '0-0-1',
        timing: 'At night',
        duration: '30 days',
      },
    ],
    advices: [
      'Low sodium (salt) diet, avoid papad, pickles, and packaged snacks',
      '30 minutes brisk walking daily',
      'Maintain weekly home BP monitoring log',
    ],
    investigations: ['Lipid Profile', 'KFT (Serum Creatinine, Urea)', 'ECG'],
  },
];

export const SEED_COMMON_DIAGNOSES = [
  'Viral Fever',
  'Hypertension',
  'Diabetes Mellitus',
  'URTI (Upper Respiratory Tract Infection)',
  'Acute Gastroenteritis',
  'Migraine / Tension Headache',
  'Allergic Rhinitis',
  'Acid Peptic Disorder / GERD',
  'Urinary Tract Infection (UTI)',
  'Osteoarthritis',
];

export const SEED_COMMON_INVESTIGATIONS = [
  'CBC (Complete Blood Count)',
  'HbA1c',
  'Blood Sugar (Fasting & PP)',
  'LFT (Liver Function Test)',
  'KFT (Kidney Function Test)',
  'Lipid Profile',
  'Urine Routine & Micro',
  'Thyroid Profile (T3, T4, TSH)',
  'Serum Uric Acid',
  'ECG',
  'Chest X-Ray',
];

export const SEED_COMMON_ADVICES = [
  'Drink plenty of water (8-10 glasses daily)',
  'Take adequate rest and avoid heavy work',
  'Avoid oily, spicy, and street food',
  'Eat freshly prepared, light warm meals',
  'Steam inhalation and salt water gargling',
  'Check and record blood pressure daily',
  'Monitor morning fasting blood glucose',
  'Return immediately if symptoms worsen or high fever persists',
];

export const SEED_COMMON_MEDICINES = [
  { name: 'Paracetamol 500 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-1', defaultTiming: 'After food' },
  { name: 'Paracetamol 650 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-1', defaultTiming: 'After food' },
  { name: 'Cetirizine 10 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '0-0-1', defaultTiming: 'At night' },
  { name: 'Pantoprazole 40 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-0', defaultTiming: 'Empty stomach' },
  { name: 'Pantoprazole + Domperidone', form: 'Capsule', defaultDose: '1 capsule', defaultFreq: '1-0-0', defaultTiming: 'Empty stomach' },
  { name: 'Amoxicillin + Clavulanic Acid 625 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-1', defaultTiming: 'After food' },
  { name: 'Azithromycin 500 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-0', defaultTiming: 'After food' },
  { name: 'Telmisartan 40 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-0', defaultTiming: 'After food' },
  { name: 'Amlodipine 5 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '0-0-1', defaultTiming: 'At night' },
  { name: 'Metformin 500 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-1', defaultTiming: 'With food' },
  { name: 'Glimepiride 1 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-0', defaultTiming: 'Before food' },
  { name: 'Atorvastatin 10 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '0-0-1', defaultTiming: 'At night' },
  { name: 'Ibuprofen 400 mg', form: 'Tablet', defaultDose: '1 tablet', defaultFreq: '1-0-1', defaultTiming: 'After food' },
  { name: 'ORS (Oral Rehydration Salts)', form: 'Drops', defaultDose: '1 sachet in 1L water', defaultFreq: 'SOS', defaultTiming: 'After food' },
  { name: 'Cough Syrup (Levosalbutamol + Guaiphenesin)', form: 'Syrup', defaultDose: '10 ml', defaultFreq: '1-0-1', defaultTiming: 'After food' },
];

// Pre-seeded past visits for returning patient Rahul Patil
export const SEED_PAST_VISITS: Visit[] = [
  {
    id: 'V-2026-101',
    patientId: 'P-1001',
    patientName: 'Rahul Patil',
    patientAge: 42,
    patientGender: 'Male',
    visitType: 'New',
    date: '2026-08-10T10:00:00.000Z',
    status: 'Completed',
    symptoms: [
      { id: 's-1', name: 'Headache', duration: '5 days', severity: 'Moderate' },
      { id: 's-2', name: 'Occasional Dizziness', duration: '2 days', severity: 'Mild' },
    ],
    clinicalNotes: 'Occasional occipital heaviness after late work hours. BP elevated on examination.',
    vitals: {
      bpSystolic: 146,
      bpDiastolic: 92,
      pulse: 80,
      temperature: 98.4,
      spO2: 98,
      weight: 74,
    },
    diagnoses: [{ id: 'd-1', name: 'Hypertension Stage 1' }],
    prescription: {
      id: 'rx-101',
      visitId: 'V-2026-101',
      patientId: 'P-1001',
      date: '2026-08-10',
      diagnoses: [{ id: 'd-1', name: 'Hypertension Stage 1' }],
      medicines: [
        {
          id: 'rx-m1',
          medicineName: 'Amlodipine 5 mg',
          form: 'Tablet',
          dosage: '1 tablet',
          frequency: '0-0-1',
          timing: 'At night',
          duration: '30 days',
          instructions: 'Take regularly after dinner',
        },
      ],
      advices: [
        'Salt restricted diet (< 5g daily)',
        'Start 30 mins brisk walking',
        'Maintain daily morning blood pressure log',
      ],
      investigations: ['Lipid Profile', 'KFT', 'ECG'],
      followUpText: 'After 30 days',
      createdAt: '2026-08-10T10:30:00.000Z',
    },
    investigations: [{ id: 'inv-1', testName: 'Lipid Profile' }, { id: 'inv-2', testName: 'ECG' }],
    advices: ['Salt restricted diet', 'Daily 30 min brisk walk'],
    followUp: 'After 30 days',
    bill: {
      id: 'b-101',
      visitId: 'V-2026-101',
      patientId: 'P-1001',
      consultationFee: 500,
      investigationCharges: 0,
      otherCharges: 0,
      discount: 0,
      totalAmount: 500,
      payment: {
        id: 'pay-101',
        amount: 500,
        method: 'UPI',
        status: 'Paid',
        paidAt: '2026-08-10T10:35:00.000Z',
      },
      createdAt: '2026-08-10T10:35:00.000Z',
    },
    completedAt: '2026-08-10T10:35:00.000Z',
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-08-10T10:35:00.000Z',
  },
  {
    id: 'V-2026-102',
    patientId: 'P-1001',
    patientName: 'Rahul Patil',
    patientAge: 42,
    patientGender: 'Male',
    visitType: 'Follow-up',
    date: '2026-09-12T11:00:00.000Z',
    status: 'Completed',
    symptoms: [
      { id: 's-3', name: 'Follow-up checkup', duration: '1 day', severity: 'Mild' },
    ],
    clinicalNotes: 'BP well controlled on Amlodipine 5mg. Headache subsided completely.',
    vitals: {
      bpSystolic: 124,
      bpDiastolic: 82,
      pulse: 74,
      temperature: 98.6,
      spO2: 99,
      weight: 73,
    },
    diagnoses: [{ id: 'd-2', name: 'Hypertension (Well Controlled)' }],
    prescription: {
      id: 'rx-102',
      visitId: 'V-2026-102',
      patientId: 'P-1001',
      date: '2026-09-12',
      diagnoses: [{ id: 'd-2', name: 'Hypertension (Well Controlled)' }],
      medicines: [
        {
          id: 'rx-m2',
          medicineName: 'Amlodipine 5 mg',
          form: 'Tablet',
          dosage: '1 tablet',
          frequency: '0-0-1',
          timing: 'At night',
          duration: '30 days',
          instructions: 'Continue regular bedtime dose',
        },
      ],
      advices: ['Continue reduced salt diet', 'Continue regular walking'],
      investigations: [],
      followUpText: 'After 30 days',
      createdAt: '2026-09-12T11:25:00.000Z',
    },
    investigations: [],
    advices: ['Continue reduced salt diet', 'Continue regular walking'],
    followUp: 'After 30 days',
    bill: {
      id: 'b-102',
      visitId: 'V-2026-102',
      patientId: 'P-1001',
      consultationFee: 300,
      investigationCharges: 0,
      otherCharges: 0,
      discount: 0,
      totalAmount: 300,
      payment: {
        id: 'pay-102',
        amount: 300,
        method: 'Cash',
        status: 'Paid',
        paidAt: '2026-09-12T11:30:00.000Z',
      },
      createdAt: '2026-09-12T11:30:00.000Z',
    },
    completedAt: '2026-09-12T11:30:00.000Z',
    createdAt: '2026-09-12T11:00:00.000Z',
    updatedAt: '2026-09-12T11:30:00.000Z',
  },
];
